version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: dockerbuild-cache

      - run: docker-compose run --rm test
      - run: bash <(curl -s https://codecov.io/bash)

      - save_cache:
          key: dockerbuild-cache
          paths:
            - .dockerbuild