version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
            - dockerbuild-cache-{{ checksum "go.mod" }}
            - dockerbuild-cache-

      - run: docker-compose run --rm test
      - run: bash <(curl -s https://codecov.io/bash)
      - run: sudo chown -R circleci:circleci .dockerbuild

      - save_cache:
          key: dockerbuild-cache-{{ checksum "go.mod" }}
          paths:
            - .dockerbuild/